-- AlterTable
ALTER TABLE "FitnessAssessment" ADD COLUMN     "bloodPressure" TEXT,
ADD COLUMN     "hba1c" DOUBLE PRECISION,
ADD COLUMN     "t3" DOUBLE PRECISION,
ADD COLUMN     "t4" DOUBLE PRECISION,
ADD COLUMN     "tsh" DOUBLE PRECISION;
